#!/usr/bin/python

import os
import sys
import shutil
import re
import optparse
import os.path

from bcv import git_version

# =============================================================================
#
#                               PREAMBLE
#
# =============================================================================

def parse_commandline():
        """
        Parse the options given on the command-line.
        """
        parser = optparse.OptionParser(usage = __doc__,version=git_version.verbose_msg)

        parser.add_option("-p", "--path", help="Path to output directory.",default = 'output')
	parser.add_option("-T", "--threshold", help="Manual threshold.",default = 0.9)
	parser.add_option("-m", "--manual", help="Manual threshold, on or off.",default = 1)
	parser.add_option("-M", "--matName", help="Name of matrix to scan.",default = 'bisp')
	parser.add_option("-f", "--mfile", help="Name of file to scan.",default = 'test.mat')
        opts, args = parser.parse_args()
        return opts

# =============================================================================
#
#                                    Main
#
# =============================================================================
def main():
        ## parse the command line
        opts = parse_commandline()
	pathN = opts.path
	HbThresh = opts.threshold
	threshMan = opts.manual
	mName = opts.matName
	fName = opts.mfile

	#threshScan( fName, mName, threshMan, HbThresh, pathN)
	cmd = 'source inputfiles/MatlabSetup_R2008a_glnxa64.sh; threshScan %s %s %d %f %s'%(fName, mName, int(threshMan), float(HbThresh), pathN)
        print cmd

        os.system(cmd)
if __name__ == "__main__":
    main()	
