function [Hd] = notch_filter(Fpass1,Fstop1,Fstop2,Fpass2,Fs)
%NOTCH_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 09-Jul-2015 13:04:45

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
% Fs = 512;  % Sampling Frequency
% 
% Fpass1 = 59;          % First Passband Frequency
% Fstop1 = 59.5;        % First Stopband Frequency
% Fstop2 = 60.5;        % Second Stopband Frequency
% Fpass2 = 61;          % Second Passband Frequency
Apass1 = 0.5;         % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
%Astop  = 10;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
